vsphere:
  tags_category:
      name: cat-abc
      description: "abc-description"
      cardinality: "MULTIPLE"
      associable_types:
        - "Folder"
        - "VirtualMachine"
      tags:
        abc-l0:
          description: "tag description"
        newtag-l0:
          description: "tag description"
        abc-l1:
          description: "tag description"
