---
nsxt:
  display_name: example-vm-segment
  segment_cidr: 10.50.0.1/24
  dhcp_config:
    # If false, all other dhcp values are ignored
    enable: true
    name: example-vm-segment-dhcp-profile
    ranges:
      - 10.50.0.10-10.50.0.19
    dns_servers:
      - 8.8.8.8
      - 1.1.1.1
    dhcp_generic_options:
      -
        code: 119
        values: ["example.com"]
...