---
vsphere:
  resource_pools:
    -
      name: terraform-resource-pool-test
      datacenter: Datacenter
      location: Cluster/management-1
      role_assignments:
        permission1:
          user_or_group: vsphere.local\\DCClients
          is_group: true
          propagate: true
          role: Monitoring-Role
        permission2:
          user_or_group: vsphere.local\\DCClients
          is_group: true
          propagate: true
          role: Monitoring-Role
    -
      name: child-resource-pool-test
      datacenter: Datacenter
      location: ResourcePool/terraform-resource-pool-test
      role_assignments:
        permission1:
          user_or_group: vsphere.local\\DCClients
          is_group: true
          propagate: true
          role: No access
        permission2:
          user_or_group: vsphere.local\\DCClients
          is_group: true
          propagate: true
          role: No access
    -
      name: host-resource-pool-test
      datacenter: Datacenter
      location: Host/esxi-117486.aceafe9a.asia-southeast1.gve.goog
      role_assignments:
        permission1:
          user_or_group: vsphere.local\\DCClients
          is_group: true
          propagate: true
          role: Monitoring-Role
        permission2:
          user_or_group: vsphere.local\\DCClients
          is_group: true
          propagate: true
          role: Monitoring-Role
