---
nsxt:
  # This needs to be the name of the tier1 gateway created with the base nsx module
  display_name: example_pool
  algorithm: IP_HASH
  min_active_members: 2
  members:
    foo1:
      ip_address: "10.51.0.69"
    foo2:
      ip_address: "10.51.0.96"
  tags:
    env: dev
  snat:
    type: AUTOMAP
  tcp_multiplexing_enabled: true