---
nsxt:
  policy_name: example-firewall_policy
  rules:
    -
      display_name: allow-icmp
      disabled: false
      # action may be ALLOW, DROP, or REJECT
      action: ALLOW
      # direction may be IN, OUT, or IN_OUT
      direction: IN_OUT
      logged: false
      services:
        # There are a number of built-in services. Their names can be gathered through the NSX-T UI
        - ICMP ALL
        - DNS
        - SSH
      # destination_groups can specify 'ANY' with an empty list '[]'
      destination_groups: []
    -
      display_name: allow-ssh
      disabled: false
      action: ALLOW
      direction: IN_OUT
      logged: false
      services:
        # If you have custom services defined you can specify them by their key name
        - example-port88
        - example-port8888
      destination_groups:
        - 10.50.0.0/24
    -
      display_name: drop-all
      disabled: false
      action: DROP
      direction: IN
      logged: false
      # Empty list is ALL
      services: []
      destination_groups:
        - 10.50.0.0/24
  tags:
    foo: bar
    bar: foo
  custom_l4_services:
    example-port88:
      description: Sample TCP port 88
      tags:
        foo: bar
      # TCP or UDP
      protocol: TCP
      destination_ports:
        - 88
      source_ports: []
    example-port8888:
      description: Sample TCP port 8888
      protocol: TCP
      destination_ports:
        - 8888
      source_ports: []
...