vsphere:
  folders_tags_category:
    - name: cat-abc123
      description: "abc-description"
      cardinality: "MULTIPLE"
    - name: cat-abcd134
      description: "abc-description"
      cardinality: "MULTIPLE"
    - name: cat-xyz144
      description: "xyz-description"
      cardinality: "SINGLE"
  folders_custom_attributes:
    - name: "abc.xyz.Custom.Attrobutes"
    - name: "abc1.xyz1.Custom1.Attributes11"
  folders:
    level0:
      - datacenter: Datacenter
        path: folder11
        type: vm
        custom_attributes:
          - name: "abc.xyz.Custom.Attrobutes"
            value: "myvalue"
          - name: "abc1.xyz1.Custom1.Attributes11"
            value: "my2value"
        tags:
          - name: abc
            description: "tag description"
            category_name: cat-abc123
          - name: abc-2
            description: "tag description"
            category_name: cat-abc123   
        role_assignments:
          permission1:
            user_or_group: vsphere.local\\ExternalIPDUsers
            is_group: true
            propagate: true
            role: Monitoring-Role
          permission2:
            user_or_group: vsphere.local\\DCClients
            is_group: true
            propagate: true
            role: Monitoring-Role
    level1:
      - datacenter: Datacenter
        path: folder11/folder12
        type: vm
        role_assignments: {}
        custom_attributes:
          - name: "abc.xyz.Custom.Attrobutes"
            value: "myvalue"
          - name: "abc1.xyz1.Custom1.Attributes11"
            value: "my2value"
        tags:
          - name: abc
            description: "tag description"
            category_name: cat-abc123
      - datacenter: Datacenter
        path: folder11/folder13
        type: vm
        role_assignments:
          permission1:
            user_or_group: vsphere.local\\ExternalIPDUsers
            is_group: true
            propagate: true
            role: Monitoring-Role
          permission2:
            user_or_group: vsphere.local\\DCClients
            is_group: true
            propagate: true
            role: Monitoring-Role
        custom_attributes:
          - name: "abc.xyz.Custom.Attrobutes"
            value: "myvalue"
          - name: "abc1.xyz1.Custom1.Attributes11"
            value: "my2value"
        tags:
          - name: abc
            description: "tag description"
            category_name: cat-abc123
      - datacenter: Datacenter
        path: folder11/folder15
        type: vm
        role_assignments:
          permission1:
            user_or_group: vsphere.local\\ExternalIPDUsers
            is_group: true
            propagate: true
            role: Monitoring-Role
          permission2:
            user_or_group: vsphere.local\\DCClients
            is_group: true
            propagate: true
            role: Monitoring-Role
        custom_attributes:
          - name: "abc.xyz.Custom.Attrobutes"
            value: "myvalue"
          - name: "abc1.xyz1.Custom1.Attributes11"
            value: "my2value"
        tags:
          - name: abc
            description: "tag description"
            category_name: cat-abc123

