vsphere:
  folder:
    datacenter: Datacenter
    path: folder111
    type: vm
    custom_attributes: {}
      # "abc.xyz.Custom.Attrobute": "myvalue"
      # "abc1.xyz1.Custom1.Attributes11": "my2value"
    tags: {}
      # abc-l0:
      #   category_name: cat-abc
      # newtag-l0:
      #   category_name: cat-abc
    role_assignments:
      permission1:
        user_or_group: vsphere.local\\ExternalIPDUsers
        is_group: true
        propagate: true 
        role: Monitoring-Role
      permission2:
        user_or_group: vsphere.local\\DCClients
        is_group: true
        propagate: true
        role: Monitoring-Role

